services:
  order-creation-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - order-service-network
  
  order-processing-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    restart: unless-stopped
    networks:
      - order-service-network
  
  gateway:
    image: ghcr.io/mibrgmv/order-service-gateway:latest
    platform: linux/arm64
    networks:
      - order-service-network
    ports:
      - "8000:5187"
    restart: unless-stopped
    environment:
      OrderCreationService__Prefix: http
      OrderCreationService__Host: order-creation-service
      OrderCreationService__Port: 8080
      OrderProcessingService__Prefix: http
      OrderProcessingService__Host: order-processing-service
      OrderProcessingService__Port: 8081
  
  order-creation-service:
    image: ghcr.io/mibrgmv/order-creation-service:latest
    platform: linux/arm64
    networks:
      - order-service-network
    depends_on:
      - order-creation-postgres
      - kafka
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      Postgres__Host: order-creation-postgres
      Postgres__Port: 5432
      Postgres__Database: postgres
      Postgres__Username: postgres
      Postgres__Password: postgres
      Postgres__SslMode: Prefer
      Kafka__Configuration__BootstrapServers: kafka:9094
  
  order-processing-service:
    image: ghcr.io/mibrgmv/order-processing-service:latest
    platform: linux/arm64
    networks:
      - order-service-network
    depends_on:
      - order-processing-postgres
      - kafka
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      Postgres__Host: order-processing-postgres
      Postgres__Port: 5432
      Postgres__Database: postgres
      Postgres__Username: postgres
      Postgres__Password: postgres
      Postgres__SslMode: Prefer
      Kafka__Configuration__BootstrapServers: kafka:9094
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - order-service-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        order_creation:1:1,
        order_processing:1:1,
    depends_on:
      - zookeeper
    networks:
      - order-service-network
    volumes:
      - order-service-kafka-data:/kafka-data
    ports:
      - "8001:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - order-service-network
    ports:
      - "8003:8003"
    volumes:
      - ./src/Presentation/OrderProcessingService.Presentation.Kafka/protos:/schemas # change path to your local proto directory
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.order_creation: orders.OrderCreationKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.order_processing: orders.OrderProcessingKey

      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.order_creation: orders.OrderCreationValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.order_processing: orders.OrderProcessingValue

networks:
  order-service-network:
    driver: bridge

volumes:
  order-service-kafka-data: